version: 1.0.{build}

branches: 
  only:
    - master

environment:
  global:
    APPVEYOR_OS_NAME: windows
  matrix:
  #MSYS2 Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      BUILDER: MSYS2
      CCACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\.ccache"

  #VisualStudio Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      BUILDER : VS
      BITS: 32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      BUILDER : VS
      BITS: 64

configuration: Debug
shallow_clone: true
clone_depth: 5

init:
- set MSYS2_PATH=c:\msys64
- set CHERE_INVOKING=1
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x86" set MSYSTEM=MINGW32
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x64" set MSYSTEM=MINGW64
- '%MSYS2_PATH%\usr\bin\bash -lc "pacman --noconfirm -S --needed unzip rsync"'
- if "%BUILDER%"=="VS" set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%

cache:
    - .ccache

install:
- cd ..
- git clone --depth=1 --branch=master https://github.com/openframeworks/openFrameworks
- call openFrameworks\scripts\ci\addons\install.cmd

before_build:
- if "%BUILDER%"=="MSYS2" (%MSYS2_PATH%\usr\bin\bash -lc "ccache -z")
- if "%BUILDER%"=="MSYS2" (%MSYS2_PATH%\usr\bin\bash -lc "ccache -s")

build_script:
- cd %OF_PATH%
- scripts\ci\addons\build.cmd

